### ISSUE TITLE
work with redux-saga

### ISSUE THREAD

**Issue by sayjeyhi** [labcodes/react-redux-api-tools#7]
Could we use this middle-ware with saga ?
how to use `call` effect with this? specially if we have some `api` sequence of requests

**Comment by lucianoratamero** [comment]
@jafar-rezaei thanks for the comment!

for that specific purpose, I've created another lib (that uses react-redux-api-tools behind the scenes) to deal with almost any data flow you may need; request chaining included.

I'd recommend you take a look at it: https://github.com/labcodes/rel-events

but if you don't want to use it, no worries; just propose a way that this lib could be used with sagas and we can take a look at the support for it! I've never used sagas myself, since I don't really love the paradigm, but we could work on it. :)

**Comment by sayjeyhi** [comment]
I did not tried this middle-ware yet , I should have a try to night with saga and will give you the feedback :)

**Comment by sayjeyhi** [comment]
@lucianoratamero thanks to this good middleware, this is good to use with `thunks` , but to use with `redux-saga` I found another great library which could help handling API requests .
https://github.com/klis87/redux-saga-requests

thanks
